import Head from 'next/head';
import Navbar from '../Navbar';
import { Inter } from 'next/font/google'

import styles from './MainLayout.module.css';

const inter = Inter({ subsets: ['latin'] })
const MainLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Home - Sandro</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={`${styles.main} ${inter.className}`}>
                {children}
            </main>
        </>
      )
}
 
export default MainLayout;